# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8879c9360b7c88fd22420dadca160ffaf4392efa0ba66ffe13039701394d56d4010f6dc68557a4538523237975aa6744946b6383527066cf2e42f87cdca52182

test:
  secret_key_base: 30a0d7da43913537d69c8de5710fab4ee465b91119b2d20dc616a52cb6426dd7888b479a46c12f75cb22374a19124708dfe8e8bbbcf62c4c939f9a62e6d034b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
